# Generated by Django 5.0.6 on 2024-07-04 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lesson", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userexerciseattempt",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="userexerciseattempt",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userlessonprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userlessonprogress",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="userlessonprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="image",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="question",
        ),
        migrations.AddField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                choices=[
                    ("WRITTEN_SPOKEN", "Written and Spoken"),
                    ("FILL_BLANKS", "Fill the Blanks"),
                    ("TRANSFORM", "Transform Phrase"),
                ],
                default="WRITTEN_SPOKEN",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exercise",
            name="lesson",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="Lesson.lesson",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exercise",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("correct_answer", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="Lesson.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("exercise", "order")},
            },
        ),
        migrations.CreateModel(
            name="UserExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("last_attempted_question", models.IntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Lesson.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "exercise")},
            },
        ),
        migrations.CreateModel(
            name="UserQuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("written_attempt", models.TextField(blank=True, null=True)),
                ("spoken_attempt", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Lesson.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "question")},
            },
        ),
        migrations.DeleteModel(
            name="ExerciseOption",
        ),
        migrations.DeleteModel(
            name="UserExerciseAttempt",
        ),
        migrations.DeleteModel(
            name="UserLessonProgress",
        ),
    ]
