# Generated by Django 5.0.6 on 2024-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lesson", "0002_remove_userexerciseattempt_exercise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="exercise_images/"
            ),
        ),
    ]
